version: '3'

services:
  jekyll:
    # Not technically "new" or the same as what's on github-pages, but close
    # enough and new enough
    image: docker.io/jekyll/jekyll:latest
    environment:
      - JEKYLL_ENV=development
      # The Jekyll image seems to require us to manually set the UID/GID
      # for non-root containers
      - JEKYLL_UID=1001
      - JEKYLL_GID=1001
    command: jekyll serve --livereload --drafts --force_polling --incremental
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
