version: '3.9'

x-podman:
  in_pod: false

services:
  jekyll:
    # Not technically "new" or the same as what's on github-pages, but close
    # enough and new enough
    image: docker.io/jekyll/jekyll:latest
    environment:
      # Use a volume local gem store, as default user jekyll:jekyll can't write to /usr
      - GEM_HOME=/srv/jekyll/.gem
      - JEKYLL_ENV=development
    # Important to bind to 0.0.0.0 for rootless, or it won't expose to host correctly
    command: bundle exec jekyll serve --livereload --drafts --force_polling --incremental --host 0.0.0.0 -P 4000
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    # Map inner jekyll:jekyll to host user
    userns_mode: keep-id
